const COUNTRY_CURRENCY_MAP = {
  Afghanistan:               { symbol: '؋',    code: 'AFN', locale: 'ps-AF' },
  Albania:                   { symbol: 'Lek',  code: 'ALL', locale: 'sq-AL' },
  Algeria:                   { symbol: 'DA',   code: 'DZD', locale: 'ar-DZ' },
  Andorra:                   { symbol: '€',    code: 'EUR', locale: 'ca-AD' },
  Angola:                    { symbol: 'Kz',   code: 'AOA', locale: 'pt-AO' },
  Argentina:                 { symbol: '$',    code: 'ARS', locale: 'es-AR' },
  Armenia:                   { symbol: '֏',    code: 'AMD', locale: 'hy-AM' },
  Australia:                 { symbol: 'A$',   code: 'AUD', locale: 'en-AU' },
  Austria:                   { symbol: '€',    code: 'EUR', locale: 'de-AT' },
  Azerbaijan:                { symbol: '₼',    code: 'AZN', locale: 'az-AZ' },
  Bahamas:                   { symbol: 'B$',   code: 'BSD', locale: 'en-BS' },
  Bahrain:                   { symbol: 'BD',   code: 'BHD', locale: 'ar-BH' },
  Bangladesh:                { symbol: '৳',    code: 'BDT', locale: 'bn-BD' },
  Barbados:                  { symbol: 'Bds$', code: 'BBD', locale: 'en-BB' },
  Belarus:                   { symbol: 'Br',   code: 'BYN', locale: 'be-BY' },
  Belgium:                   { symbol: '€',    code: 'EUR', locale: 'nl-BE' },
  Belize:                    { symbol: 'BZ$',  code: 'BZD', locale: 'en-BZ' },
  Bhutan:                    { symbol: 'Nu.',  code: 'BTN', locale: 'dz-BT' },
  Bolivia:                   { symbol: 'Bs.',  code: 'BOB', locale: 'es-BO' },
  'Bosnia and Herzegovina':  { symbol: 'KM',   code: 'BAM', locale: 'bs-BA' },
  Botswana:                  { symbol: 'P',    code: 'BWP', locale: 'en-BW' },
  Brazil:                    { symbol: 'R$',   code: 'BRL', locale: 'pt-BR' },
  Brunei:                    { symbol: 'B$',   code: 'BND', locale: 'ms-BN' },
  Bulgaria:                  { symbol: 'лв',   code: 'BGN', locale: 'bg-BG' },
  Cambodia:                  { symbol: '៛',    code: 'KHR', locale: 'km-KH' },
  Cameroon:                  { symbol: 'FCFA', code: 'XAF', locale: 'fr-CM' },
  Canada:                    { symbol: 'C$',   code: 'CAD', locale: 'en-CA' },
  Chile:                     { symbol: '$',    code: 'CLP', locale: 'es-CL' },
  China:                     { symbol: '¥',    code: 'CNY', locale: 'zh-CN' },
  Colombia:                  { symbol: '$',    code: 'COP', locale: 'es-CO' },
  'Costa Rica':              { symbol: '₡',    code: 'CRC', locale: 'es-CR' },
  Croatia:                   { symbol: '€',    code: 'EUR', locale: 'hr-HR' },
  Cuba:                      { symbol: '$',    code: 'CUP', locale: 'es-CU' },
  Cyprus:                    { symbol: '€',    code: 'EUR', locale: 'el-CY' },
  'Czech Republic':          { symbol: 'Kč',   code: 'CZK', locale: 'cs-CZ' },
  Denmark:                   { symbol: 'kr.',  code: 'DKK', locale: 'da-DK' },
  'Dominican Republic':      { symbol: 'RD$',  code: 'DOP', locale: 'es-DO' },
  Ecuador:                   { symbol: '$',    code: 'USD', locale: 'es-EC' },
  Egypt:                     { symbol: 'E£',   code: 'EGP', locale: 'ar-EG' },
  'El Salvador':             { symbol: '$',    code: 'USD', locale: 'es-SV' },
  Estonia:                   { symbol: '€',    code: 'EUR', locale: 'et-EE' },
  Ethiopia:                  { symbol: 'Br',   code: 'ETB', locale: 'am-ET' },
  Europe:                    { symbol: '€',    code: 'EUR', locale: 'de-DE' },
  Fiji:                      { symbol: 'FJ$',  code: 'FJD', locale: 'en-FJ' },
  Finland:                   { symbol: '€',    code: 'EUR', locale: 'fi-FI' },
  France:                    { symbol: '€',    code: 'EUR', locale: 'fr-FR' },
  Georgia:                   { symbol: '₾',    code: 'GEL', locale: 'ka-GE' },
  Germany:                   { symbol: '€',    code: 'EUR', locale: 'de-DE' },
  Ghana:                     { symbol: 'GH₵',  code: 'GHS', locale: 'ak-GH' },
  Greece:                    { symbol: '€',    code: 'EUR', locale: 'el-GR' },
  Guatemala:                 { symbol: 'Q',    code: 'GTQ', locale: 'es-GT' },
  Honduras:                  { symbol: 'L',    code: 'HNL', locale: 'es-HN' },
  'Hong Kong':               { symbol: 'HK$',  code: 'HKD', locale: 'zh-HK' },
  Hungary:                   { symbol: 'Ft',   code: 'HUF', locale: 'hu-HU' },
  Iceland:                   { symbol: 'kr',   code: 'ISK', locale: 'is-IS' },
  India:                     { symbol: '₹',    code: 'INR', locale: 'en-IN' },
  Indonesia:                 { symbol: 'Rp',   code: 'IDR', locale: 'id-ID' },
  Iran:                      { symbol: '﷼',    code: 'IRR', locale: 'fa-IR' },
  Iraq:                      { symbol: 'ID',   code: 'IQD', locale: 'ar-IQ' },
  Ireland:                   { symbol: '€',    code: 'EUR', locale: 'en-IE' },
  Israel:                    { symbol: '₪',    code: 'ILS', locale: 'he-IL' },
  Italy:                     { symbol: '€',    code: 'EUR', locale: 'it-IT' },
  Jamaica:                   { symbol: 'J$',   code: 'JMD', locale: 'en-JM' },
  Japan:                     { symbol: '¥',    code: 'JPY', locale: 'ja-JP' },
  Jordan:                    { symbol: 'JD',   code: 'JOD', locale: 'ar-JO' },
  Kazakhstan:                { symbol: '₸',    code: 'KZT', locale: 'kk-KZ' },
  Kenya:                     { symbol: 'KSh',  code: 'KES', locale: 'sw-KE' },
  Kuwait:                    { symbol: 'KD',   code: 'KWD', locale: 'ar-KW' },
  Lebanon:                   { symbol: 'L£',   code: 'LBP', locale: 'ar-LB' },
  Libya:                     { symbol: 'LD',   code: 'LYD', locale: 'ar-LY' },
  Luxembourg:                { symbol: '€',    code: 'EUR', locale: 'lb-LU' },
  Macau:                     { symbol: 'MOP$', code: 'MOP', locale: 'zh-MO' },
  Madagascar:                { symbol: 'Ar',   code: 'MGA', locale: 'mg-MG' },
  Malaysia:                  { symbol: 'RM',   code: 'MYR', locale: 'ms-MY' },
  Maldives:                  { symbol: 'Rf',   code: 'MVR', locale: 'dv-MV' },
  Malta:                     { symbol: '€',    code: 'EUR', locale: 'mt-MT' },
  Mauritius:                 { symbol: '₨',    code: 'MUR', locale: 'en-MU' },
  Mexico:                    { symbol: 'Mex$', code: 'MXN', locale: 'es-MX' },
  Monaco:                    { symbol: '€',    code: 'EUR', locale: 'fr-MC' },
  Mongolia:                  { symbol: '₮',    code: 'MNT', locale: 'mn-MN' },
  Montenegro:                { symbol: '€',    code: 'EUR', locale: 'cnr-ME' },
  Morocco:                   { symbol: 'DH',   code: 'MAD', locale: 'ar-MA' },
  Myanmar:                   { symbol: 'K',    code: 'MMK', locale: 'my-MM' },
  Nepal:                     { symbol: '₨',    code: 'NPR', locale: 'ne-NP' },
  Netherlands:               { symbol: '€',    code: 'EUR', locale: 'nl-NL' },
  'New Zealand':             { symbol: 'NZ$',  code: 'NZD', locale: 'en-NZ' },
  Nicaragua:                 { symbol: 'C$',   code: 'NIO', locale: 'es-NI' },
  Nigeria:                   { symbol: '₦',    code: 'NGN', locale: 'en-NG' },
  Norway:                    { symbol: 'kr',   code: 'NOK', locale: 'no-NO' },
  Oman:                      { symbol: 'RO',   code: 'OMR', locale: 'ar-OM' },
  Pakistan:                  { symbol: '₨',    code: 'PKR', locale: 'ur-PK' },
  Panama:                    { symbol: 'B/.',  code: 'PAB', locale: 'es-PA' },
  Paraguay:                  { symbol: '₲',    code: 'PYG', locale: 'es-PY' },
  Peru:                      { symbol: 'S/.',  code: 'PEN', locale: 'es-PE' },
  Philippines:               { symbol: '₱',    code: 'PHP', locale: 'fil-PH' },
  Poland:                    { symbol: 'zł',   code: 'PLN', locale: 'pl-PL' },
  Portugal:                  { symbol: '€',    code: 'EUR', locale: 'pt-PT' },
  Qatar:                     { symbol: 'QR',   code: 'QAR', locale: 'ar-QA' },
  Romania:                   { symbol: 'L',    code: 'RON', locale: 'ro-RO' },
  Russia:                    { symbol: '₽',    code: 'RUB', locale: 'ru-RU' },
  'Saudi Arabia':            { symbol: 'SR',   code: 'SAR', locale: 'ar-SA' },
  Serbia:                    { symbol: 'din.', code: 'RSD', locale: 'sr-RS' },
  Singapore:                 { symbol: 'S$',   code: 'SGD', locale: 'en-SG' },
  Slovakia:                  { symbol: '€',    code: 'EUR', locale: 'sk-SK' },
  Slovenia:                  { symbol: '€',    code: 'EUR', locale: 'sl-SI' },
  'South Africa':            { symbol: 'R',    code: 'ZAR', locale: 'en-ZA' },
  'South Korea':             { symbol: '₩',    code: 'KRW', locale: 'ko-KR' },
  Spain:                     { symbol: '€',    code: 'EUR', locale: 'es-ES' },
  'Sri Lanka':               { symbol: '₨',    code: 'LKR', locale: 'si-LK' },
  Sweden:                    { symbol: 'kr',   code: 'SEK', locale: 'sv-SE' },
  Switzerland:               { symbol: 'CHF',  code: 'CHF', locale: 'de-CH' },
  Taiwan:                    { symbol: 'NT$',  code: 'TWD', locale: 'zh-TW' },
  Thailand:                  { symbol: '฿',    code: 'THB', locale: 'th-TH' },
  Tunisia:                   { symbol: 'DT',   code: 'TND', locale: 'ar-TN' },
  Turkey:                    { symbol: '₺',    code: 'TRY', locale: 'tr-TR' },
  Ukraine:                   { symbol: '₴',    code: 'UAH', locale: 'uk-UA' },
  'United Arab Emirates':    { symbol: 'AED',  code: 'AED', locale: 'ar-AE' },
  'United Kingdom':          { symbol: '£',    code: 'GBP', locale: 'en-GB' },
  'United States':           { symbol: '$',    code: 'USD', locale: 'en-US' },
  Uruguay:                   { symbol: '$U',   code: 'UYU', locale: 'es-UY' },
  Uzbekistan:                { symbol: "so'm", code: 'UZS', locale: 'uz-UZ' },
  Venezuela:                 { symbol: 'Bs.S', code: 'VES', locale: 'es-VE' },
  Vietnam:                   { symbol: '₫',    code: 'VND', locale: 'vi-VN' },
  Yemen:                     { symbol: '﷼',    code: 'YER', locale: 'ar-YE' },
  Zambia:                    { symbol: 'ZK',   code: 'ZMW', locale: 'en-ZM' },
  Zimbabwe:                  { symbol: 'Z$',   code: 'ZWL', locale: 'en-ZW' },
};

const ALL_COUNTRIES = Object.keys(COUNTRY_CURRENCY_MAP).sort();

function getCurrencyForCountry(country) {
  return COUNTRY_CURRENCY_MAP[country] || { symbol: '₹', code: 'INR', locale: 'en-IN' };
}

module.exports = { COUNTRY_CURRENCY_MAP, ALL_COUNTRIES, getCurrencyForCountry };
